image: holgerpirk/emacs_and_latex:latest

build:
  stage: build
  script:
    - emacs -Q --batch -l ob-tangle --eval "(dolist (file command-line-args-left) (with-current-buffer (find-file-noselect file) (org-babel-tangle)))" ob-lobo.org
  artifacts:
    paths:
      - ob-lobo.el
      - ob-lobo-test.el

test:
  stage: test
  script:
    - emacs -batch -l cl -l ert -l ob-lobo.el -l ob-lobo-test.el -f ert-run-tests-batch-and-exit
